### PR TITLE
(#21): make the state of supervisor3 compatible with erlang's supervi…

### PR DESCRIPTION
**Pull request by tothlac**
…sor state

### CODE REVIEW

**Comment by robertoaloi** [comment]
I am fine with this patch for the time being, since it would solve the release handler issue discussed in https://github.com/klarna/brod/pull/382 and it's in line with what the RabbitMQ maintainers did at the time they discovered the same issue (https://github.com/rabbitmq/rabbitmq-common/pull/230/files). Of course this solution (adding the field definition, but not using it) cannot be considered a long-term one.

Generally speaking, maintaining a fork-of-a-fork for a supervisor module does not a great place to be in. Alternatives I see for the long-term:

* Switch back from supervisor3 to a standard OTP supervisor
* Create a wrapper around the supervisor which does not "fork" it, but rather extend it (if possible)

Less ideal (because of the maintenance costs):

* Port the Klarna changes from this fork to the latest version of RabbitMQ's supervisor2
* Port the Klarna changes from this fork to the latest OTP's supervisor

Of course there are other options:

* Contribute these changes to OTP
* Contribute these changes to RabbitMQ

I would like to hear @dszoboszlay and @mikpe 's opinions on this before merging.

**Review by robertoaloi — APPROVED** [review]

**Comment by mikpe** [comment]
I agree with @robertoaloi 's comment.  Preferably we should not use supervisor3 at all, but if we must, we should resync it with upstream and try to minimize the amount of local changes.

**Review by mikpe — APPROVED** [review]

**Review by suexcxine — APPROVED** [review]

**Comment by suexcxine** [comment]
I agree with @robertoaloi 's comment too, I am also using brod and encountered the same issue.

**Comment by zmstone** [comment]
It is a fork of rabbitmq.git not supervisor2.git (no such thing)
I.e. rabbitmq.git is huge, otherwise we would have considered a patch for upstream.
Also, it is a fork because of potential licensing issues

**Comment by zmstone** [comment]
WRT this pr, if the goal is to support live upgrade (runtime beam reload), don’t we need a code_change clause to update the state?

**Comment by robertoaloi** [comment]
@zmstone Definitely not suggesting to bring in the whole RabbitMQ as a dependency. What I mean is that `supervisor3` is a fork of the `supervisor2` module from RabbitMQ which in turns is a fork of OTP's `supervisor`. If we really want to maintain this fork, we should periodically sync it with (and therefore trying to rebase our changes on) the latest OTP supervisor or at least RabbitMQ supervisor2.

**Comment by robertoaloi** [comment]
Regarding the `code_change` function, the new `dynamic_restarts` feature is only used in the context of `simple-one-for-one` supervisors, which I suspect is not currently used in `brod`.

The `code_change` implementation in `supervisor3` is currently in sync with the `supervisor2` implementation from RabbitMQ and slightly different from the latest one in `supervisor` from OTP. In none of the three implementations the `dynamic_restarts` field is referred. So, nothing is needed there, from what I can tell (during an upgrade the state definition before/after used by the code_change will be the same).

Surely this is a very fragile solution, though. In next versions of OTP things could change and `supervisor3` could break in unexpected ways.

**Comment by robertoaloi** [comment]
**UPDATE**: I see what you mean, now. You are referring to the fact we are changing the definition of our own state. Yes, this could very well be the case. The `supervisor3` is a `gen_server` itself. Doesn't this mean we would not just need an extra clause, but that we should also not be able to use the record syntax in the `code_change` at all, but instead use the internal tuple representation? How is this not a problem in standard OTP? They added the extra field in the supervisor's state, but not modified the `code_change`:

https://github.com/erlang/otp/commit/264a5e804d6e23bf6c6916887669760cbf243caa#diff-fbfd7bb2c1f79df2b42a31516bd6d8a9

**Comment by zmstone** [comment]
Why isn’t there a code_chang clause in otp itself?
I guss nobody can upgrade otp version without a full beam restart?

**Comment by mikpe** [comment]
I knew about the live upgrade issue we have locally in the org.  I assumed we'd solve it by one of our usual mechanisms.  (Since live upgrade code can get messy we don't usually dirty our published open source components with it.)
As for @zmstone's question above, supervisor is a kernel application, and I assume they cannot be live-upgraded.

**Comment by zmstone** [comment]
On the other hand, I’m not sure if supervisors are suspended at all for beam reload in OTP’s release handling principal.

**Comment by robertoaloi** [comment]
@zmstone You have a point. Assuming we want `supervisor3` and as a consequence `brod` to support live upgrades we'd need to add a test case for a live upgrade in this repo. This PR represents a step in the right direction, but something else may be needed.

**Comment by zmstone** [comment]
Gave it a bit more thoughts.

A disclaimer first: I have zero experience in live upgrades as in OTP release handling principal.

Since this issue was reported from a trouble observed at a live upgrade attempt,
I'd assume that the live-upgrade (chicken) can not happen without this patch (egg),
and this patch (egg) can not be in place without an upgrade (chicken, if it has to be a live-upgrade).
i.e. there is no way to perform a live upgrade for supervisor3 anyway.

Maybe there isn't much we can do, except to add a statement in brod's changelog that
the next release does not support live-upgrade.

**Comment by dszoboszlay** [comment]
I think adding a new field to keep the `#state{}` of `supervisor3` and `supervisor` in sync is not the good solution. It will break again as soon as they touch the `supervisor` state in OTP, and looking at the code there is a much better way to fix the crash.

The crash, according to klarna/brod#381 happens in the second clause here: https://github.com/erlang/otp/blob/4c8c1538e685ce6607149683eea6279de8ced197/lib/stdlib/src/supervisor.erl#L274-L280
```erlang
    case lists:keyfind(supervisor, 1, Misc) of
	{supervisor, [{"Callback", Mod}]} ->
	    Mod;
	_ ->
	    [_Header, _Data, {data, [{"State", State}]} | _] = Misc,
	    State#state.module
    end.
```

Instead of keeping the state records in sync, why not simply add the `{supervisor, [{"Callback", Mod}]}` to the `Misc` data? This is how `supervisor` does it: https://github.com/erlang/otp/blob/4c8c1538e685ce6607149683eea6279de8ced197/lib/stdlib/src/supervisor.erl#L1591-L1595, seems to be totally portable to `supervisor3`.

**Review by dszoboszlay — CHANGES_REQUESTED** [review]
I think adding a new field to keep the `#state{}` of `supervisor3` and `supervisor` in sync is not the good solution. It will break again as soon as they touch the `supervisor` state in OTP, and looking at the code there is a much better way to fix the crash.

The crash, according to klarna/brod#381 happens in the second clause here: https://github.com/erlang/otp/blob/4c8c1538e685ce6607149683eea6279de8ced197/lib/stdlib/src/supervisor.erl#L274-L280
```erlang
    case lists:keyfind(supervisor, 1, Misc) of
	{supervisor, [{"Callback", Mod}]} ->
	    Mod;
	_ ->
	    [_Header, _Data, {data, [{"State", State}]} | _] = Misc,
	    State#state.module
    end.
```

Instead of keeping the state records in sync, why not simply add the `{supervisor, [{"Callback", Mod}]}` to the `Misc` data? This is how `supervisor` does it: https://github.com/erlang/otp/blob/4c8c1538e685ce6607149683eea6279de8ced197/lib/stdlib/src/supervisor.erl#L1591-L1595, seems to be totally portable to `supervisor3`.

**Comment by robertoaloi** [comment]
@dszoboszlay Cherry-picking that change from the current supervisor is definitely an alternative solution to the specific issue, but it feels like the underlying issue remains. The content of the `Misc` may change at any time and the new solution will still break the moment OTP changes that case clause. I still think we need to take the time to either translate `supervisor3` into a wrapper of `supervisor` or at least to "rebase" it on top of the current supervisor implementation.

**Comment by tothlac** [comment]
Of course if this issue is solved there will be probably some other problems when trying to live upgrade brod. Anyways without this step live upgrading won't work since brod's supervisor module (brod_sup) won't be suspended / stopped. I was happy to see you guys answered quickly.

**Comment by tothlac** [comment]
@dszoboszlay Dani, thanks for your advice. I've changed the pull request so now it contains the changes you've suggested. I've tried it in brod and it worked perfectly. It's a much better looking solution!

**Review by robertoaloi — APPROVED** [review]

**Review by mikpe — APPROVED** [review]

**Review by dszoboszlay — APPROVED** [review]

**Comment by dszoboszlay** [comment]
@robertoaloi I'm not so concerned about keeping the `supervisor3` fork, custom supervisor implementations are supported by OTP, see the release notes about the feature we're "cherry picking" here: http://erlang.org/doc/apps/stdlib/notes.html#stdlib-3.0

> Supervisors now explicitly add their callback module in the return from sys:get_status/1,2. This is to simplify custom supervisor implementations. The Misc part of the return value from sys:get_status/1,2 for a supervisor is now:
>
> `[{data, [{"State", State}]},{supervisor,[{"Callback",Module}]}]`
>
> *** POTENTIAL INCOMPATIBILITY ***

Regardless, I would be very happy to see a more flexible supervisor in OTP that lets you define what action to take when a supervision event happens (e.g. when a child dies whether you want to restart it immediately, after a delay or not at all; what to do with other children etc.). But this is out of scope for this ticket. :smile:

**Comment by mikpe** [comment]
Tagged as 1.1.10.

**Pull request merged**
