### PR TITLE
Fix module name in the documentation

### PR DESCRIPTION
**Pull request by alde**

### CODE REVIEW

**Comment by id** [comment]
Well, the thing is, it's a list of changes in chronological order applied to the original supervisor.erl.

First change made by rabbitmq guys was to rename it to supervisor2. Then look at #6 :)

**Comment by alde** [comment]
Yes, but the module is called supervisor3 :-)

-module(supervisor3).

which makes the readme and file comment saying something else weird to me

**Comment by id** [comment]
It's confusing, I know. But it would be wrong to put "module name is supervisor3" as number 1 on the change list anyway.

**Comment by alde** [comment]
Fair enough.

I just stumbled on it and found it a small annoyance :-)

**Pull request closed without merging**
